import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Provider from "@/lib/providers";
import "@/styles/globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="border-b flex space-x-4">
          <Link href="/">Todos A</Link>
          <Link href="/todos">Todos B</Link>
        </div>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
